#!/usr/bin/env python3
"""
Raya Forensic PDF Report Generator
Generates executive & technical malware triage reports from Raya ScanResult JSON.
"""

import sys
import json
import argparse
from datetime import datetime, timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super(NumberedCanvas, self).showPage()
        super(NumberedCanvas, self).save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "RAYA THREAT TRIAGE REPORT — CONFIDENTIAL & PROPRIETARY")
            self.drawRightString(612 - 54, 750, datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(54, 742, 612 - 54, 742)
            
        # Footer (all pages)
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(54, 45, 612 - 54, 45)
        self.drawString(54, 32, "Generated by Raya • Threat Detection & Binary Analysis Engine")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 54, 32, page_text)
        self.restoreState()

def generate_pdf(report_data, output_path):
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#475569"),
        spaceAfter=12
    )
    h2_style = ParagraphStyle(
        'Heading2_Custom',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=17,
        textColor=colors.HexColor("#1E293B"),
        spaceBefore=14,
        spaceAfter=6
    )
    body_style = ParagraphStyle(
        'Body_Custom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#1E293B")
    )
    code_style = ParagraphStyle(
        'Code_Custom',
        parent=styles['Normal'],
        fontName='Courier',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#0F172A")
    )
    table_cell = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#1E293B")
    )
    table_cell_bold = ParagraphStyle(
        'TableCellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#0F172A")
    )
    badge_style = ParagraphStyle(
        'BadgeStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=11,
        textColor=colors.white,
        alignment=1
    )

    story = []

    # Title & Header
    story.append(Paragraph("RAYA BINARY TRIAGE & FORENSIC REPORT", title_style))
    story.append(Paragraph("High-Throughput Threat Detection & Binary Forensics Engine", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0F172A"), spaceAfter=12))

    # Threat Banner
    matches = report_data.get("matches", [])
    has_critical = any(m.get("severity") == "critical" for m in matches)
    has_high = any(m.get("severity") == "high" for m in matches)
    
    if has_critical:
        verdict_text = "VERDICT: CRITICAL THREAT DETECTED (MALICIOUS)"
        banner_bg = colors.HexColor("#DC2626")
    elif has_high:
        verdict_text = "VERDICT: HIGH-SEVERITY SUSPICIOUS BINARY"
        banner_bg = colors.HexColor("#EA580C")
    elif matches:
        verdict_text = f"VERDICT: {len(matches)} RULE(S) TRIGGERED"
        banner_bg = colors.HexColor("#D97706")
    else:
        verdict_text = "VERDICT: CLEAN / NO MATCHES DETECTED"
        banner_bg = colors.HexColor("#16A34A")

    banner_table = Table([[Paragraph(f"<b>{verdict_text}</b>", badge_style)]], colWidths=[504])
    banner_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), banner_bg),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(banner_table)
    story.append(Spacer(1, 12))

    # Target Metadata Summary
    hashes = report_data.get("hashes", {})
    file_size = report_data.get("file_size", 0)
    size_str = f"{file_size:,} bytes ({file_size / (1024*1024):.2f} MB)" if file_size > 1024*1024 else f"{file_size:,} bytes ({file_size / 1024:.2f} KB)"
    entropy = report_data.get("entropy", 0.0)
    entropy_str = f"{entropy:.2f} / 8.00 ({'High/Packed' if entropy > 7.0 else 'Moderate' if entropy > 6.0 else 'Normal'})"

    meta_rows = [
        [Paragraph("<b>Target File:</b>", table_cell_bold), Paragraph(report_data.get("target", "unknown"), code_style)],
        [Paragraph("<b>Binary Format:</b>", table_cell_bold), Paragraph(report_data.get("file_type", "unknown"), table_cell)],
        [Paragraph("<b>File Size:</b>", table_cell_bold), Paragraph(size_str, table_cell)],
        [Paragraph("<b>Entropy:</b>", table_cell_bold), Paragraph(entropy_str, table_cell)],
        [Paragraph("<b>Scan Duration:</b>", table_cell_bold), Paragraph(f"{report_data.get('scan_duration_ms', 0.0):.2f} ms", table_cell)],
    ]
    meta_table = Table(meta_rows, colWidths=[110, 394])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 14))

    # Cryptographic & Forensic Hashes
    story.append(Paragraph("Cryptographic & Triage Hashes", h2_style))
    hash_rows = [
        [Paragraph("<b>MD5:</b>", table_cell_bold), Paragraph(hashes.get("md5", "N/A"), code_style)],
        [Paragraph("<b>SHA-1:</b>", table_cell_bold), Paragraph(hashes.get("sha1", "N/A"), code_style)],
        [Paragraph("<b>SHA-256:</b>", table_cell_bold), Paragraph(hashes.get("sha256", "N/A"), code_style)],
    ]
    if hashes.get("imphash"):
        hash_rows.append([Paragraph("<b>IMPHASH:</b>", table_cell_bold), Paragraph(f"<b>{hashes['imphash']}</b>", code_style)])
    if hashes.get("exphash"):
        hash_rows.append([Paragraph("<b>EXPHASH:</b>", table_cell_bold), Paragraph(f"<b>{hashes['exphash']}</b>", code_style)])
    if hashes.get("rich_hash"):
        hash_rows.append([Paragraph("<b>Rich Header Hash:</b>", table_cell_bold), Paragraph(f"<b>{hashes['rich_hash']}</b>", code_style)])
    if hashes.get("ssdeep"):
        hash_rows.append([Paragraph("<b>SSDEEP:</b>", table_cell_bold), Paragraph(hashes["ssdeep"], code_style)])

    hash_table = Table(hash_rows, colWidths=[130, 374])
    hash_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#F1F5F9")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(hash_table)
    story.append(Spacer(1, 14))

    # PE Structure & Section Analysis (if available)
    pe_info = report_data.get("pe_info")
    if pe_info and "sections" in pe_info:
        story.append(Paragraph("PE Structure & Section Forensics", h2_style))
        sec_header = [
            Paragraph("<b>Section</b>", table_cell_bold),
            Paragraph("<b>Virt Addr</b>", table_cell_bold),
            Paragraph("<b>Virt Size</b>", table_cell_bold),
            Paragraph("<b>Raw Size</b>", table_cell_bold),
            Paragraph("<b>Entropy</b>", table_cell_bold),
            Paragraph("<b>Flags</b>", table_cell_bold),
        ]
        sec_rows = [sec_header]
        for s in pe_info["sections"]:
            ent = s.get("entropy", 0.0)
            flags = []
            if s.get("is_readable"): flags.append("R")
            if s.get("is_writable"): flags.append("W")
            if s.get("is_executable"): flags.append("X")
            flag_str = "".join(flags)
            is_rwx = flag_str == "RWX"
            flag_color = "#DC2626" if is_rwx else "#0F172A"
            ent_color = "#DC2626" if ent > 7.0 else "#D97706" if ent > 6.0 else "#16A34A"
            
            sec_rows.append([
                Paragraph(f"<b>{s.get('name')}</b>", table_cell_bold),
                Paragraph(f"0x{s.get('virtual_address', 0):08X}", code_style),
                Paragraph(f"{s.get('virtual_size', 0):,} B", table_cell),
                Paragraph(f"{s.get('raw_size', 0):,} B", table_cell),
                Paragraph(f"<font color='{ent_color}'><b>{ent:.2f}</b></font>", table_cell),
                Paragraph(f"<font color='{flag_color}'><b>{flag_str}</b></font>", table_cell),
            ])
        sec_table = Table(sec_rows, colWidths=[80, 85, 85, 85, 85, 84])
        sec_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(sec_table)
        story.append(Spacer(1, 14))

    # Detection Matches
    story.append(Paragraph(f"Detection Findings ({len(matches)} Rule Matches)", h2_style))
    if not matches:
        story.append(Paragraph("<i>No detection rules were triggered during this scan. The binary appears benign under the active ruleset.</i>", body_style))
    else:
        for idx, m in enumerate(matches, 1):
            sev = m.get("severity", "medium").upper()
            sev_color = colors.HexColor("#DC2626") if sev == "CRITICAL" else colors.HexColor("#EA580C") if sev == "HIGH" else colors.HexColor("#D97706")
            
            rule_header = [
                [
                    Paragraph(f"<b>#{idx} {m.get('rule')}</b>", table_cell_bold),
                    Paragraph(f"<b>[{sev}]</b>", ParagraphStyle('SevBadge', parent=badge_style, textColor=sev_color, alignment=2))
                ]
            ]
            rule_hdr_table = Table(rule_header, colWidths=[400, 104])
            rule_hdr_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                ('LINEBELOW', (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),
            ]))
            
            rule_body = []
            if m.get("description"):
                rule_body.append([Paragraph("<b>Description:</b>", table_cell_bold), Paragraph(m["description"], table_cell)])
            if m.get("mitre_technique"):
                rule_body.append([Paragraph("<b>MITRE ATT&CK:</b>", table_cell_bold), Paragraph(f"<b>{m['mitre_technique']}</b>", table_cell)])
            if m.get("tags"):
                rule_body.append([Paragraph("<b>Tags:</b>", table_cell_bold), Paragraph(", ".join(m["tags"]), table_cell)])
            
            # Evidence items
            evidence_items = m.get("evidence", [])
            evidence_lines = []
            for ev in evidence_items:
                if isinstance(ev, dict):
                    if "StringMatch" in ev:
                        sm = ev["StringMatch"]
                        offsets = ", ".join([f"0x{o:08x}" for o in sm.get("offsets", [])[:3]])
                        evidence_lines.append(f"• String <code>{sm.get('id')}</code> matched {sm.get('count')} time(s) at {offsets}")
                    elif "PeCharacteristic" in ev:
                        pc = ev["PeCharacteristic"]
                        evidence_lines.append(f"• PE Characteristic: <b>{pc.get('name')}</b> — {pc.get('detail')}")
                    elif "Imphash" in ev:
                        evidence_lines.append(f"• Import Hash (Imphash) Match: <code>{ev['Imphash'].get('imphash')}</code>")
                    elif "TlsCallback" in ev:
                        tc = ev["TlsCallback"]
                        addrs = ", ".join([f"0x{a:x}" for a in tc.get("addresses", [])[:3]])
                        evidence_lines.append(f"• TLS Pre-Execution Callbacks: <b>{tc.get('count')} callback(s)</b> at [{addrs}]")
                    elif "Exphash" in ev:
                        evidence_lines.append(f"• Export Hash Match: <code>{ev['Exphash'].get('exphash')}</code>")
                    elif "PeSectionEntropy" in ev:
                        pse = ev["PeSectionEntropy"]
                        evidence_lines.append(f"• High Section Entropy: <code>{pse.get('section')}</code> ({pse.get('entropy'):.2f} / 8.0)")
                    elif "PeSectionFlag" in ev:
                        psf = ev["PeSectionFlag"]
                        evidence_lines.append(f"• Suspicious Section Flag: <code>{psf.get('section')}</code> has <b>{psf.get('flag')}</b>")
                    elif "StackString" in ev:
                        ss = ev["StackString"]
                        evidence_lines.append(f"• Deobfuscated Stack String: <b>\"{ss.get('value')}\"</b> at VA 0x{ss.get('offset', 0):X}")
                    elif "CryptoConstant" in ev:
                        cc = ev["CryptoConstant"]
                        evidence_lines.append(f"• Cryptographic Constant [{cc.get('algorithm')}]: {cc.get('description')} at offset 0x{cc.get('offset', 0):X}")
                    elif "DotNetIndicator" in ev:
                        evidence_lines.append(f"• .NET CLR Indicator: <code>{ev['DotNetIndicator'].get('indicator')}</code>")
                    elif "GoIndicator" in ev:
                        evidence_lines.append(f"• Go Runtime Indicator: <code>{ev['GoIndicator'].get('indicator')}</code>")
                    elif "RustIndicator" in ev:
                        evidence_lines.append(f"• Rust Runtime Indicator: <code>{ev['RustIndicator'].get('indicator')}</code>")
                    elif "RichAnomaly" in ev:
                        evidence_lines.append(f"• Rich Header Anomaly: <b>{ev['RichAnomaly'].get('detail')}</b>")
                    elif "Custom" in ev:
                        evidence_lines.append(f"• {ev['Custom']}")
                    else:
                        evidence_lines.append(f"• {json.dumps(ev)}")
            
            if evidence_lines:
                rule_body.append([
                    Paragraph("<b>Forensic Evidence:</b>", table_cell_bold),
                    Paragraph("<br/>".join(evidence_lines), table_cell)
                ])
                
            rule_detail_table = Table(rule_body, colWidths=[110, 394])
            rule_detail_table.setStyle(TableStyle([
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor("#FAFAFA")),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            
            story.append(KeepTogether([rule_hdr_table, rule_detail_table, Spacer(1, 10)]))

    # Raya Automated Triage Guidance Section
    story.append(Spacer(1, 10))
    story.append(Paragraph("Automated Triage & Incident Response Pipeline Guidance", h2_style))
    guidance_p = Paragraph(
        "<b>Downstream SIEM & Threat Intelligence Export:</b><br/>"
        "To export structured findings for SOC automation and ticketing pipelines, execute:<br/>"
        "<code>raya scan &quot;" + report_data.get("target", "") + "&quot; --rules rules/ --format sarif &gt; incident.sarif</code><br/>"
        "<code>raya scan &quot;" + report_data.get("target", "") + "&quot; --rules rules/ --format stix &gt; bundle.json</code><br/><br/>"
        "<b>In-Memory Archive & Drop Inspection:</b><br/>"
        "If this sample drops encrypted archives during triage, pass the password directly or rely on Raya's auto-triage:<br/>"
        "<code>raya scan drop.zip --rules rules/ --password infected</code>",
        table_cell
    )
    guidance_table = Table([[guidance_p]], colWidths=[504])
    guidance_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#EFF6FF")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#93C5FD")),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(guidance_table)

    # Build Document
    doc.build(story, canvasmaker=NumberedCanvas)
    print(f"[+] Successfully generated forensic PDF report: {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Generate Raya Forensic PDF Report")
    parser.add_argument("--json", "-j", help="Path to Raya scan JSON file (reads stdin if omitted)")
    parser.add_argument("--output", "-o", default="sample_report.pdf", help="Output PDF file path")
    args = parser.parse_args()

    if args.json:
        with open(args.json, "r") as f:
            data = json.load(f)
    else:
        data = json.load(sys.stdin)

    # If the JSON is a list (e.g. from multiple file scans), take the first or primary match
    if isinstance(data, list):
        if not data:
            print("[-] Empty scan result list", file=sys.stderr)
            sys.exit(1)
        data = data[0]

    generate_pdf(data, args.output)

if __name__ == "__main__":
    main()
